### ISSUE TITLE
没有正确模拟 CPU 寄存器的 P 寄存器 Unused 位固定为 1

### ISSUE THREAD

**Issue by yinxulai** [qpalzmqaz123/tsnes#4]
但是似乎目前没有发现兼容性问题，我看你的注释里都写了，但是没有实现其逻辑
![image](https://user-images.githubusercontent.com/22045569/92681588-a3e00900-f360-11ea-91b8-2d5c2bd7bb87.png)

**Comment by qpalzmqaz123** [comment]
以前 plp 和 rti 的时候把 U 给清零了，问题已解决，谢谢！
